<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;


class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        DB::table('products')->insert([
            [
                'sku' => 'P220424002',
                'nama_produk' => 'JMK Jamu & Pil Habis Bersalin 40 Har 
                750g',
                'jumlah_barang' => 0,
                'harga_beli' => 200000,
                'harga_jual' => 220000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424003',
                'nama_produk' => 'JMK Jamu Klingsir | Hernia (Turun Berok) (25 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 15000,
                'harga_jual' => 20000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424004',
                'nama_produk' => 'JMK Jamu Kuat Pria (50 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424005',
                'nama_produk' => 'JMK Jamu Sehat Wanita (100 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 35000,
                'harga_jual' => 45000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424006',
                'nama_produk' => 'JMK Jamu Pegal Linu (50 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424007',
                'nama_produk' => 'JMK Jamu Pelangsing (30 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424008',
                'nama_produk' => 'JMK Jamu Detox (60 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 40000,
                'harga_jual' => 50000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424009',
                'nama_produk' => 'JMK Jamu Kuat Lelaki (10 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 15000,
                'harga_jual' => 20000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424010',
                'nama_produk' => 'JMK Jamu Pegal Linu (5 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 10000,
                'harga_jual' => 15000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424011',
                'nama_produk' => 'JMK Jamu Pelangsing (10 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 20000,
                'harga_jual' => 25000,
                'created_at' => now(),
                'kadaluarsa' => now()->addMonths(12),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424012',
                'nama_produk' => 'JMK Jamu Pegal Linu (10 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 20000,
                'harga_jual' => 25000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424013',
                'nama_produk' => 'JMK Jamu Kuat Lelaki (8 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 15000,
                'harga_jual' => 20000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424014',
                'nama_produk' => 'JMK Jamu Pelangsing (12 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424015',
                'nama_produk' => 'JMK Jamu Detox (15 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424016',
                'nama_produk' => 'JMK Jamu Peninggi Badan (20 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 35000,
                'harga_jual' => 40000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424017',
                'nama_produk' => 'JMK Jamu Awet Muda (30 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 40000,
                'harga_jual' => 45000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424018',
                'nama_produk' => 'JMK Jamu Diabetes (25 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424019',
                'nama_produk' => 'JMK Jamu Anemia (40 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 45000,
                'harga_jual' => 50000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424020',
                'nama_produk' => 'JMK Jamu Kolesterol (20 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 35000,
                'harga_jual' => 40000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424021',
                'nama_produk' => 'JMK Jamu Maag (15 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424022',
                'nama_produk' => 'JMK Jamu Asam Urat (15 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424023',
                'nama_produk' => 'JMK Jamu Darah Tinggi (10 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424024',
                'nama_produk' => 'JMK Jamu Pegal Linu (20 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 40000,
                'harga_jual' => 45000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424025',
                'nama_produk' => 'JMK Jamu Rematik (30 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 35000,
                'harga_jual' => 40000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424026',
                'nama_produk' => 'JMK Jamu PMS (20 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424027',
                'nama_produk' => 'JMK Jamu Sakit Pinggang (10 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 20000,
                'harga_jual' => 25000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424028',
                'nama_produk' => 'JMK Jamu Batuk (15 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424029',
                'nama_produk' => 'JMK Jamu Flu (20 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424030',
                'nama_produk' => 'JMK Jamu Masuk Angin (25 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 35000,
                'harga_jual' => 40000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424031',
                'nama_produk' => 'JMK Jamu Anemia (15 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 20000,
                'harga_jual' => 25000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424032',
                'nama_produk' => 'Jamu Sehat Herbalindo Asam Urat (20 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 40000,
                'harga_jual' => 45000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424033',
                'nama_produk' => 'Jamu Dewa Tangan Darah Tinggi (30 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 35000,
                'harga_jual' => 40000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424034',
                'nama_produk' => 'Jamu Kecantikan Puteri Remaja (15 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424035',
                'nama_produk' => 'Jamu Sinar Gemilang PMS (25 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 45000,
                'harga_jual' => 50000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424036',
                'nama_produk' => 'Jamu Hutan Rempah Batuk (10 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 20000,
                'harga_jual' => 25000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424037',
                'nama_produk' => 'Jamu Alam Semesta Flu (20 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424038',
                'nama_produk' => 'Jamu Rempah Nusantara Masuk Angin (15 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424039',
                'nama_produk' => 'Jamu Nusantara Flu (30 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 40000,
                'harga_jual' => 45000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424040',
                'nama_produk' => 'Jamu Tradisi Nusantara Masuk Angin (25 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 35000,
                'harga_jual' => 40000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424041',
                'nama_produk' => 'Jamu Dewa Sehat Anemia (20 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424042',
                'nama_produk' => 'Jamu Sejahtera Herbal Darah Tinggi (10 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424043',
                'nama_produk' => 'Jamu Bumi Sehat Asam Urat (15 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424044',
                'nama_produk' => 'Jamu Alami Lestari Pelangsing (20 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 35000,
                'harga_jual' => 40000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424045',
                'nama_produk' => 'Jamu Tradisional Sembuhkan Flu (25 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 40000,
                'harga_jual' => 45000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424046',
                'nama_produk' => 'Jamu Herbal Nusantara Pegal Linu (10 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 20000,
                'harga_jual' => 25000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424047',
                'nama_produk' => 'Jamu Alami Sehatkan Perut Batuk (15 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424048',
                'nama_produk' => 'Jamu Semesta Lestari Awet Muda (20 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 35000,
                'harga_jual' => 40000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424049',
                'nama_produk' => 'Jamu Alami Sehatkan Nusantara Masuk Angin (25 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 40000,
                'harga_jual' => 45000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424050',
                'nama_produk' => 'Jamu Herbal Sembuhkan Batuk (30 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 45000,
                'harga_jual' => 50000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424051',
                'nama_produk' => 'Jamu Alami Penyembuh Masuk Angin (15 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424052',
                'nama_produk' => 'Jamu Iboe Darah Tinggi (10 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424053',
                'nama_produk' => 'Jamu Iboe Asam Urat (15 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424054',
                'nama_produk' => 'Jamu Iboe Pelangsing (20 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 35000,
                'harga_jual' => 40000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424055',
                'nama_produk' => 'Jamu Iboe Flu (25 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 40000,
                'harga_jual' => 45000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424056',
                'nama_produk' => 'Jamu Iboe Pegal Linu (10 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 20000,
                'harga_jual' => 25000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424057',
                'nama_produk' => 'Jamu Iboe Awet Muda (15 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 25000,
                'harga_jual' => 30000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424058',
                'nama_produk' => 'Jamu Iboe Maag (20 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 35000,
                'harga_jual' => 40000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424059',
                'nama_produk' => 'Jamu Iboe Anemia (25 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 40000,
                'harga_jual' => 45000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424060',
                'nama_produk' => 'Jamu Iboe Masuk Angin (30 sachet)',
                'jumlah_barang' => 0,
                'harga_beli' => 45000,
                'harga_jual' => 50000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'P220424061',
                'nama_produk' => 'Jamu Iboe Kecantikan (15 kapsul)',
                'jumlah_barang' => 0,
                'harga_beli' => 30000,
                'harga_jual' => 35000,
                'kadaluarsa' => now()->addMonths(12),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Tambahkan data lainnya sesuai kebutuhan
        ]);
    }
}
